Repository APPSCHOOL2-Android/FinalProject-DongNation, pull requests merged in 2023-09, with the labels that each got.

#10 Feat: 권한 설정 UI 구현
  app/src/main/java/likelion/project/dongnation/ui/permission/PermissionFragment.kt
  app/src/main/res/drawable/shape_rect.xml
  app/src/main/res/layout/fragment_permission.xml
  app/src/main/res/values/strings-permission.xml
Labels: UI

#32 Feat: 버전 별 권한 대응 #5
  app/src/main/AndroidManifest.xml
  app/src/main/java/likelion/project/dongnation/ui/main/MainActivity.kt
Labels: FIx

#30 Feat : 리뷰를 확인할 수 있는 RecyclerView 추가 #17
  app/src/main/java/likelion/project/dongnation/ui/donate/DonateAdapter.kt
  app/src/main/java/likelion/project/dongnation/ui/donate/DonateInfoFragment.kt
  app/src/main/res/drawable/ic_donation_24dp.xml
  app/src/main/res/layout/fragment_donate_info.xml
  app/src/main/res/layout/item_review_list.xml
Labels: Feature, UI

#34 [Feat] 리뷰 보는 화면 UI 구현 #24
  app/src/main/java/likelion/project/dongnation/ui/review/ReviewShowFragment.kt
  app/src/main/res/layout/fragment_review_show.xml
  app/src/main/res/layout/item_review_list.xml
Labels: Feature, UI

#42 [Feature] 설정 클릭 시 주소 업데이트 #8
  app/src/main/java/likelion/project/dongnation/db/remote/UserDataSource.kt
  app/src/main/java/likelion/project/dongnation/repository/UserRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingViewModel.kt
Labels: Feature

#48 [Feat] 지역 선택 아이템 크기 디바이스 별 대응 #8
  app/src/main/res/layout/item_region.xml
  app/src/main/res/values-hdpi/dimes.xml
  app/src/main/res/values-mdpi/dimes.xml
  app/src/main/res/values-xhdpi/dimes.xml
  app/src/main/res/values-xxhdpi/dimes.xml
  app/src/main/res/values-xxxhdpi/dimes.xml
  app/src/main/res/values/dimes.xml
Labels: FIx

#51 [Design] UI 수정 #17
  app/src/main/res/layout/fragment_donate_info.xml
Labels: FIx, UI

#53 [Design] 리뷰 화면 UI 수정 #24
  app/src/main/java/likelion/project/dongnation/ui/review/ReviewShowFragment.kt
  app/src/main/res/layout/fragment_review_show.xml
Labels: FIx, UI

#54 Design : 상세 화면 tab UI 설정 #17
  app/src/main/res/layout/fragment_donate_info.xml
Labels: UI

#61 [Feat] 팁 게시글 수정 화면 구현
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardModifyFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/main/MainActivity.kt
  app/src/main/res/layout/fragment_board_modify.xml
Labels: Feature, UI

#70 [Feat] 게시판 작성글/댓글 화면 구현
  app/src/main/java/likelion/project/dongnation/ui/main/MainActivity.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoBoardFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoFragment.kt
  app/src/main/res/drawable/shape_board_type.xml
  app/src/main/res/layout/fragment_user_info_board.xml
  app/src/main/res/layout/item_user_info_board_write.xml
Labels: Feature, UI

#79 [Fix] bundle 저장 값 변경 #2
  app/src/main/java/likelion/project/dongnation/model/Donations.kt
  app/src/main/java/likelion/project/dongnation/ui/home/HomeAdapter.kt
Labels: FIx

#81 [Fix] 리뷰 수를 전달하도록 변경 #17
  app/src/main/java/likelion/project/dongnation/ui/donate/DonateInfoFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/donate/DonateReviewAdapter.kt
Labels: FIx

#82 [Feat] 리뷰 상세 화면 구현 #24
  app/src/main/java/likelion/project/dongnation/ui/review/ReviewShowFragment.kt
  app/src/main/res/layout/fragment_review_show.xml
Labels: Feature

#87 [Design] 저장하기 버튼 수정 #55
  app/src/main/res/layout/fragment_donate_write.xml
Labels: FIx, UI

#88 [Feat] 사용자 주소 표시 #2
  app/src/main/java/likelion/project/dongnation/ui/home/HomeFragment.kt
Labels: Feature

#89 [Feat] 팁 게시글 작성 버튼 클릭시 DB 에 저장 #26
  app/build.gradle.kts
  app/src/main/java/likelion/project/dongnation/ui/board/BoardWriteFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/gallery/GalleryFragment.kt
  app/src/main/res/layout/fragment_board_write.xml
  buildSrc/src/main/kotlin/Versions.kt
Labels: Feature, UI

#90 [Feat] 팁 게시판 화면에 DB 연결 #16
  app/src/main/java/likelion/project/dongnation/model/Tips.kt
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardMainFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
Labels: Feature

#93 [Feature] 팁 게시판 내용 화면에 DB 연결 #43
  app/src/main/java/likelion/project/dongnation/model/Tips.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsViewPagerAdapter.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardMainFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/main/MainActivity.kt
  app/src/main/res/layout/fragment_board_contents.xml
Labels: Feature

#97 [Feat] 이미지가 있을 경우 썸네일 표시 #2
  app/src/main/java/likelion/project/dongnation/ui/home/HomeAdapter.kt
Labels: Feature

#99 [Feat] 로그인 유저 분기 처리 구현
  app/src/main/java/likelion/project/dongnation/ui/login/LoginFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/login/LoginViewModel.kt
  app/src/main/java/likelion/project/dongnation/ui/main/MainActivity.kt
Labels: Feature

#103 [Feat] 스크롤 복원 구현 #2
  app/src/main/java/likelion/project/dongnation/ui/home/DiffCallback.kt
  app/src/main/java/likelion/project/dongnation/ui/home/HomeAdapter.kt
  app/src/main/java/likelion/project/dongnation/ui/home/HomeFragment.kt
Labels: Feature

#104 [Feat] 팁 게시글 수정을 하면 DB에 반영되게함 #60
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardModifyFragment.kt
  app/src/main/res/layout/fragment_board_modify.xml
Labels: Feature, UI

#106 [Fix] 초기 로그인 지역 설정 오류 해결
  app/src/main/java/likelion/project/dongnation/ui/login/LoginViewModel.kt
Labels: FIx

#107 [Feat] 초기 로그인 및 동네 변경시 지역 설정 데이터 베이스 저장
  app/src/main/java/likelion/project/dongnation/db/remote/UserDataSource.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingFragment.kt
Labels: Feature, FIx

#109 [Feat] 지역설정에서 현재 위치로 이동 기능 구현
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationRegionAdapter.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingPageFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/Region.kt
Labels: Feature

#111 [Feat] 팁 게시글 삭제 기능 구현 #43
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/res/layout/item_board_contents_dialog.xml
Labels: Feature, UI

#114 [Feat] 지역설정 DB 연결
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingFragment.kt
Labels: Feature

#115 [Feat] 지역설정에서 상세 주소 가져오도록 구현
  app/src/main/java/likelion/project/dongnation/ui/locationsetting/LocationSettingFragment.kt
Labels: Feature

#116 [Feat] 팁 게시판 검색 기능 구현 #16
  app/src/main/java/likelion/project/dongnation/ui/board/BoardMainFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/res/layout/fragment_board_main.xml
  app/src/main/res/raw/raw_search.json
Labels: Feature, UI

#121 [Feat] 화면 회전 방지
  app/src/main/AndroidManifest.xml
Labels: Feature

#131 [Feat] 채팅 기능 구현
  app/src/main/java/likelion/project/dongnation/db/remote/ChattingRoomDataSource.kt
  app/src/main/java/likelion/project/dongnation/repository/ChattingRoomRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/chatting/ChattingFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/chatting/ChattingViewModel.kt
Labels: Feature

#132 [Feat] 팁 게시판에 댓글 작성하는 기능 구현 #43
  app/src/main/java/likelion/project/dongnation/model/Tips.kt
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/res/layout/fragment_board_contents.xml
Labels: Feature

#135 [Feature]댓글 수정하는 기능 구현 #133
  app/src/main/java/likelion/project/dongnation/model/Tips.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardRipplesModifyFragment.kt
Labels: Feature

#140 [Feature] 댓글 삭제하는 기능 구현 #43
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/res/layout/item_board_contents_dialog.xml
Labels: Feature

#141 [Feature] 내정보 화면에서 게시판 작성글 DB 연결 #62
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoBoardFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoFragment.kt
  app/src/main/res/layout/item_user_info_board_write.xml
Labels: Feature

#144 [Feat] 내정보 화면에서 자신이 작성한 댓글 DB 연결 #62
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/board/BoardViewModel.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoBoardFragment.kt
Labels: Feature

#148 [Feat] 홈 스켈레톤 UI 적용
  app/src/main/java/likelion/project/dongnation/repository/DonateRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/home/HomeFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/home/HomeViewModel.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_donation_loading.xml
Labels: Feature

#155 [Feat] 채팅 목록 화면 채팅방 나가기 구현
  app/src/main/java/likelion/project/dongnation/db/remote/ChattingRoomDataSource.kt
  app/src/main/java/likelion/project/dongnation/repository/ChattingRoomRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/chatting/ChattingListFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/chatting/ChattingListViewModel.kt
  app/src/main/res/layout/item_chatting_room_leaving_dialog.xml
Labels: Feature, UI

#156 [Fix] 채팅 화면 채팅 나가기 기능 테스트 코드 수정
  app/src/main/java/likelion/project/dongnation/db/remote/ChattingRoomDataSource.kt
Labels: FIx

#160 [Design] 팁 게시판 섬네일 이미지를 가운데로 정렬하고 모서리를 둥글게 나타나게함 #16
  app/src/main/java/likelion/project/dongnation/ui/board/BoardMainFragment.kt
  app/src/main/res/layout/item_board_main.xml
Labels: UI

#161 [Feat] 팁 게시판 작성자 및 댓글 작성자 프로필 DB 연결 #62
  app/src/main/java/likelion/project/dongnation/ui/board/BoardContentsFragment.kt
  app/src/main/res/layout/fragment_board_contents.xml
  app/src/main/res/layout/item_board_contents_comment.xml
Labels: Feature

#180 [Feat] 소셜 계정 연결 중지 기능 구현
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoViewModel.kt
Labels: Feature

#181 [Feat] 계정 탈퇴 유저 데이터 삭제 기능 구현
  app/src/main/java/likelion/project/dongnation/db/remote/ChattingRoomDataSource.kt
  app/src/main/java/likelion/project/dongnation/db/remote/ReviewDataSource.kt
  app/src/main/java/likelion/project/dongnation/db/remote/UserDataSource.kt
  app/src/main/java/likelion/project/dongnation/repository/BoardRepository.kt
  app/src/main/java/likelion/project/dongnation/repository/ChattingRoomRepository.kt
  app/src/main/java/likelion/project/dongnation/repository/DonateRepository.kt
  app/src/main/java/likelion/project/dongnation/repository/ReviewRepository.kt
  app/src/main/java/likelion/project/dongnation/repository/UserRepository.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoFragment.kt
  app/src/main/java/likelion/project/dongnation/ui/userInfo/UserInfoViewModel.kt
Labels: Feature
